server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql:///demo?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-producter
  security:
    user:
      name: test
      password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8000/eureka/
    fetch-registry: true
    register-with-eureka: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
