server:
  port: 8003

spring:
  application:
    name: demo-api
  security:
    user:
      name: test
      password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8000/eureka/
    fetch-registry: true
    register-with-eureka: true